version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.15.2
    container_name: prometheus
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './prometheus/rules:/etc/prometheus/rules'
    ports:
      - 9090:9090
    restart: always
    networks:
      - prom
    depends_on:
      - alertmanager
  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    volumes:
      - './alertmanager:/etc/alertmanager'
    ports:
      - 9093:9093
    restart: always
    networks:
      - prom
  grafana:
    image: grafana/grafana:6.5.2-ubuntu
    container_name: grafana
    volumes:
      - 'grafana-pv:/var/lib/grafana'
    ports:
      - 3000:3000
    restart: always
    networks:
      - prom
    depends_on:
      - prometheus

volumes:
  grafana-pv:
    driver: local

networks:
  prom:
    ipam:
      driver: default
      config:
      - subnet: "172.21.18.0/24"
